spring:
  application:
    name: fintech-wallet-platform
  data:
    mongodb:
      uri: mongodb://localhost:27017/fintech_wallet_platform
      auto-index-creation: true

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    root: INFO
    com.example.proyecto_final: DEBUG

app:
  programadas:
    procesador:
      enabled: true
      intervalo-ms: 60000
      retraso-inicial-ms: 10000
